site_name: vpsAdminOS
theme: cosmo
extra_css: ['extra.css']
pages:
- Home: 'index.md'
- User Guide:
    - Setup: 'user-guide/setup.md'
    - User namespaces: 'user-guide/users.md'
    - Containers: 'user-guide/containers.md'
    - Networking: 'user-guide/networking.md'
    - Resources: 'user-guide/resources.md'
    - Mounts: 'user-guide/mounts.md'
- Containers:
    - Administration: 'containers/administration.md'
    - 'Export/Import': 'containers/export_import.md'
    - Migrations: 'containers/migrations.md'
- Migration Paths:
    - Converter: 'migration-paths/converter.md'
    - OpenVZ Legacy: 'migration-paths/openvz-legacy.md'
- osctld:
    - Distribution support: 'osctld/distributions.md'
    - Interfaces: 'osctld/interfaces.md'
    - 'OS requirements': 'osctld/os_requirements.md'
- Specifications:
    - Container image: 'specifications/container-image.md'
