site_name: vpsAdminOS
theme: readthedocs
extra_css: ['extra.css']
pages:
- Home: 'index.md'
- User Guide:
    - Setup: 'user-guide/setup.md'
    - User namespaces: 'user-guide/users.md'
    - Containers: 'user-guide/containers.md'
    - Networking: 'user-guide/networking.md'
    - Resources: 'user-guide/resources.md'
    - Mounts: 'user-guide/mounts.md'
- Containers:
    - Administration: 'containers/administration.md'
    - Templates: 'containers/templates.md'
    - Datasets: 'containers/datasets.md'
    - Auto starting: 'containers/auto-starting.md'
    - Resources: 'containers/resources.md'
    - Devices: 'containers/devices.md'
    - 'Export/Import': 'containers/export-import.md'
    - Migrations: 'containers/migrations.md'
- Migration Paths:
    - Converter: 'migration-paths/converter.md'
    - OpenVZ Legacy: 'migration-paths/openvz-legacy.md'
- osctld:
    - Distribution support: 'osctld/distributions.md'
    - cgroups: 'osctld/cgroups.md'
    - Interfaces: 'osctld/interfaces.md'
    - Development: 'osctld/development.md'
    - OS requirements: 'osctld/os-requirements.md'
- Specifications:
    - Container image: 'specifications/container-image.md'
    - Template repository: 'specifications/template-repository.md'
    - Distributions: 'specifications/distributions.md'
